import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface PDFContent {
    originalText: string;
    grammarResult: {
        correctedText: string;
        mistakes: { original: string; correction: string; explanation: string }[];
    } | null;
    professionalText: string | null;
    casualText: string | null;
    date: string;
}

export const generateA4Report = (content: PDFContent) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;

    // --- Header & Branding ---
    doc.setFillColor(15, 23, 42); // slate-900
    doc.rect(0, 0, pageWidth, 40, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.setFont('helvetica', 'bold');
    doc.text('TalkLift AI', margin, 20);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(148, 163, 184); // slate-400
    doc.text(`Performance Report • ${content.date}`, margin, 32);

    let currentY = 55;

    // --- Section: Original Text ---
    doc.setTextColor(15, 23, 42);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('Original Text', margin, currentY);
    currentY += 8;

    doc.setFont('helvetica', 'normal');
    doc.setTextColor(51, 65, 85); // slate-700
    const originalLines = doc.splitTextToSize(content.originalText, pageWidth - (margin * 2));
    doc.text(originalLines, margin, currentY);
    currentY += (originalLines.length * 7) + 10;

    // --- Section: Professional & Casual Tones ---
    const drawToneBox = (title: string, text: string, color: [number, number, number]) => {
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(color[0], color[1], color[2]);
        doc.text(title, margin, currentY);
        currentY += 6;

        doc.setFont('helvetica', 'normal');
        doc.setTextColor(51, 65, 85);
        const lines = doc.splitTextToSize(text, pageWidth - (margin * 2));
        doc.text(lines, margin, currentY);
        currentY += (lines.length * 7) + 12;
    };

    if (content.professionalText) {
        drawToneBox('Professional Tone', content.professionalText, [147, 51, 234]); // purple-600
    }

    if (content.casualText) {
        drawToneBox('Natural / Casual Flow', content.casualText, [16, 185, 129]); // emerald-600
    }

    // --- Section: Grammar Analysis ---
    if (content.grammarResult && content.grammarResult.mistakes.length > 0) {
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(220, 38, 38); // red-600
        doc.text('Grammar Correction Breakdown', margin, currentY);
        currentY += 8;

        autoTable(doc, {
            startY: currentY,
            margin: { left: margin, right: margin },
            head: [['Original', 'Correction', 'Explanation']],
            body: content.grammarResult.mistakes.map(m => [m.original, m.correction, m.explanation]),
            headStyles: { fillColor: [248, 250, 252], textColor: [15, 23, 42], fontStyle: 'bold' },
            bodyStyles: { textColor: [51, 65, 85] },
            alternateRowStyles: { fillColor: [249, 250, 251] },
            theme: 'striped'
        });

        currentY = (doc as any).lastAutoTable.finalY + 15;
    } else if (content.grammarResult) {
        doc.setFont('helvetica', 'italic');
        doc.setTextColor(100, 116, 139);
        doc.text('No grammatical errors found. Perfect score!', margin, currentY);
        currentY += 15;
    }

    // --- Footer ---
    const pageCount = (doc as any).internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setDrawColor(226, 232, 240);
        doc.line(margin, 280, pageWidth - margin, 280);
        doc.setFontSize(8);
        doc.setTextColor(148, 163, 184);
        doc.text('Generated by TalkLift AI', margin, 287);
        doc.text(`Page ${i} of ${pageCount}`, pageWidth - margin - 15, 287);
    }

    doc.save(`TalkLift_Report_${content.date.replace(/[/, :]/g, '_')}.pdf`);
};
